apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spu-cache.configMapName" . }}
  namespace: {{ include "spu-cache.namespace" . }}
  labels:
    {{- include "spu-cache.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
