apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spu-cache.secretName" . }}
  namespace: {{ include "spu-cache.namespace" . }}
  labels:
    {{- include "spu-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
